### ISSUE TITLE
Add config for enabling Istio.

### ISSUE THREAD

**Issue by MarvinCai** [streamnative/terraform-aws-cloud#28]
By default external-dns will watch for Istio resources, while Istio is not installed by default and there's no config to change that.
So I think we should either let external-dns not watch Istio resources by default or add config to allow installation of Istio.

**Comment by MarvinCai** [comment]
Seems Istio installation is now part of terraform-helm-charts, but when installing this module, terraform-helm-charts is not installed so might be good to able to coordinate it.

**Comment by jrsdav** [comment]
We're now (optionally) installing Istio directly in this module (it is disabled by default). This was a requirement since the bootstrap sequence is much cleaner when the Istio mesh is configured prior to installing our operators, which come later via `streamnative/terraform-helm-charts`. See the following PR: https://github.com/streamnative/terraform-aws-cloud/pull/31

Additionally, the logic for enabling/disabling dependencies for istio (such as the external-dns sources) is now more cohesive and requires just a single input: `enable_istio_operator`. See the following commit: https://github.com/streamnative/terraform-aws-cloud/commit/628d93639644eecc8e9b802539a42f62cda32088
