### ISSUE TITLE
Custom tag for AWS LB controller is causing reconcile error

### ISSUE THREAD

**Issue by MarvinCai** [streamnative/terraform-aws-cloud#29]
Seeing following error from aws lb controller pod when trying to provision lb:
`{"level":"error","ts":1636430448.8260977,"logger":"controller-runtime.manager.controller.service","msg":"Reconciler error","name":"pulsar-cluster-proxy-external","namespace":"rxrevu","error":"ValidationError: 1 validation error detected: Value '\"Vendor\":\"StreamNative' at 'tags.1.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$\n\tstatus code: 400, request id: 42c6fa19-adf4-4c87-bc17-2c32b03da3a8"}`
Seem the custom tag is causing this, remove following param from deployment fix the issue
- --default-tags=0="Vendor":"StreamNative"
Might want to fix the tag format.

**Comment by jrsdav** [comment]
I've temporarily removed this tag for now (it was added as part of the permission boundary work), but I'll keep this issue open until I can come up with a better approach for managing this tag through helm.

**Comment by addisonj** [comment]
@jrsdav The reason this is failing is due to the helm chart improperly formatting the tag in the startup of the cluster.

See `--default-tags=0="Vendor":"StreamNative"` is what is getting passed where it should be `--default-tags=Vendor=StreamNative` so I think we just need to fix the helm chart input
